name: First Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Good morning
        run: echo "Good Morining"
      - name: Print Good Bye
        run: echo "Good Bye"

