name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print good morning
        run: echo "Hello from first-action.yml"
      - name: print good bye
        run: echo "Goodbye from first-action.yml"
